version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "MatchingGame/MatchingGame.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "MatchingGame/MatchingGame.csproj" }}
workflows:
  build-and-test:
    jobs:
      - build
